.eslintrc.json
.gitignore
.prettierrc.json
babel.config.json
index.html
package-lock.json
package.json

각종 초기설정을 완료하였습ㄴ디ㅏ.
- eslint 설치 및 초기설정
- prettier 설치 및 초기설정

conf: initial setting - eslint, prettier

---

App.js
index.js
server.js
src/pages/Intro.js
src/pages/Members.js
src/pages/NewGroup.js
src/pages/NotFound.js
src/pages/Records.js
src/pages/Result.js
src/pages/SignIn.js
src/pages/SignUp.js
src/pages/index.js

- `window.location.pathname`으로 현재 주소를 기준으로 렌더링합니다.
- fetchState함수를 호출하여 유저 타입을 서버에서 받아옵니다.
- `member`일 경우 해당 유저의 `organization`상태 데이터를 추가로 받아옵니다.
- `guest`일 경우, 로컬스토리지에서 `organization`상태 데이터를 추가로 받아옵니다.
- 현재 주소와 유저 타입을 비교하여 필요한 경우 리디렉션 합니다.  
- path값을 인수로 받아 상태를 변경하는 navigate함수를 만들었습니다. 
- 테스트를 위해 App.js에서 이벤트를 등록했지만, 이후 실제 이벤트를 받는 컴포넌트로 전달하여 사용할 예정입니다.

[SPA Routing] - 손재영

---

package-lock.json
package.json
webpack.config.js

- babel을 이용하여 빌드 전 트랜스파일링하도록 하였습니다
- js빌드 시 node_modules를 제외하도록 하였습니다

Conf: Add JS bundling & transfiling

---

fake-data/users-data.js
router.js
server.js
src/App.js
src/App.module.css
src/components/MainLayout.js
src/pages/Members.js
src/pages/NewGroup.js
src/pages/Records.js
src/pages/Result.js
src/pages/SignInSignUp/SignIn.js
src/pages/SignInSignUp/SignInSignUp.js
src/pages/SignInSignUp/SignInSignUp.module.css
src/pages/SignInSignUp/SignUp.js
src/pages/SignInSignUp/schema.js
src/utils/localStorage.js

Refact: This is whole new router

---

library/CBD/component.js
library/CBD/eventHandler.js
library/CBD/index.js
library/CBD/render.js
library/CBD/state.js
src/App.js

- 모든 컴포넌트에서 지역상태를 가질 수 있도록 라이브러리를 수정하였습니다
- 필요에 따라 전역 상태/지역 상태를 선택해서 사용할 수 있도록 하였습니다.
- 상태를 라이브러리의 Component 바깥으로 분리하였습니다

Feat: Improve CBD library to use local state

---

package-lock.json
package.json
server.js
webpack.config.js

- 서버가 재구동될 때 브라우저를 새로고침하게 만들었습니다
- webpack-dev-server를 사용할 필요가 없어져서 패키지를 삭제하고 webpack.config.js를 수정하였습니다

Conf: Add livereload package to reload browser

---

.eslintrc.json
package-lock.json
package.json
src/App.js
src/pages/Result/Result.js

- lodash 설치 및 import 설정
- 변수명 변경 및 bracket pair 수정

Drag and drop - hyunjung

---

library/CBD/state.js
server.js
src/App.js
src/components/MainLayout/MainLayout.js
src/components/MainLayout/SignInAndOut.js
src/pages/Members/MemberList.js
src/pages/Members/Members.js
src/pages/NewGroup/NewGroup.js
src/pages/NewGroup/SelectGroupCnt.js
src/pages/Records/RecordItem.js
src/pages/Records/RecordList.js
src/pages/Records/Records.js
src/pages/Result/Groups.js
src/pages/Result/Member.js
src/pages/Result/Result.js
src/pages/SignInSignUp/SignIn.js
src/state/index.js

- state 디렉토리를 생성하여 App.js에서 관리하던 상태를 컴포넌트 바깥에서
전역으로 관리하기로 하였습니다.
- loading과 user상태를 조작하는 함수를 생성하고, 필요한
컴포넌트에서 import해서 사용하도록 수정하였습니다
- organization 상태를 정상적으로 유지하기 위해 App.js의 init함수에서
로컬스토리지의 organization을 초기화하도록 만들었습니다
- 가독성을 위해 전역 상태를 관리하는 코드도 모듈로 분할할 수 있을지
고민중입니다
- 전역상태 중 organization 프로퍼티를 참조하고 수정하는 부분을 전면
수정하였습니다
- 상태와 관련된 변수와 함수를 모두 직접 import해서 사용하도록
수정하였습니다

Global state jaeyeong

---

server.js
src/App.js
src/pages/Members/MemberList.js
src/pages/SignInSignUp/SignIn.js
src/pages/SignInSignUp/SignUp.js
src/pages/SignInSignUp/schema.js
src/state/index.js

Fix: Fix signin signup error

---

library/SPA-router/Link.js
server.js
src/App.js
src/App.module.css
src/components/Counter/Counter.js
src/components/Counter/Counter.module.css
src/components/Loading/Loader.js
src/components/MainLayout/MainLayout.js
src/components/MainLayout/MainLayout.module.css
src/components/MainLayout/Nav.js
src/components/MainLayout/Nav.module.css
src/components/MainLayout/SignInAndOut.js
src/components/MainLayout/SignInAndOut.module.css
src/components/Modals/DeleteModal.js
src/components/Modals/SaveModal.js
src/components/Modals/SignupModal.js
src/components/Result/Groups.js
src/components/Result/Members.js
src/pages/Members/MemberItem.js
src/pages/Members/MemberList.js
src/pages/Members/Members.js
src/pages/NewGroup/NewGroup.js
src/pages/NewGroup/Result.js
src/pages/NewGroup/SelectGroupCnt.js
src/pages/NotFound.js
src/pages/Records/RecordItem.js
src/pages/Records/RecordList.js
src/pages/Records/Records.js
src/pages/SignInSignUp/SignIn.js
src/pages/SignInSignUp/SignUp.js

- 임시 레이아웃 설정
- 지금까지의 코드리뷰 반영하여 리팩토링
- 조 짜는 함수 분리하여 재사용할 수 있도록 함
- 부분 렌더링을 위해 전체적으로 구조를 변경하면서 각 컴포넌트의 render 함수를 DOMStr 함수로 변경함

Refactor - Chaerin

---

library/CBD/component.js
library/CBD/eventHandler.js
src/pages/NewGroup/NewGroup.js
src/pages/SignInSignUp/SignIn.js
src/pages/SignInSignUp/SignUp.js

- 컴포넌트의 data-component-id를 인식하지 못하는 버그를 수정하였습니다
- merge 과정에서 변수 이름이 어긋난 부분을 수정하는 중입니다.

Fix: Resolve conflict and bug - by pereng11

---

server.js
src/App.js
src/components/Counter/Counter.js
src/components/Result/Groups.js
src/core/solver.js
src/pages/Members/MemberList.js
src/pages/NewGroup/NewGroup.js
src/pages/NewGroup/Result.js
src/pages/NewGroup/SelectGroupCnt.js
src/pages/Records/RecordItem.js
src/state/index.js

- 조짜기 기능 버그를 수정하였습니다
- 조짜기 버튼의 disabled 어트리뷰트 적용 방법을 수정하였습니다
- 수동/자동 조짜기 함수를 각각 만들어서 하위 컴포넌트에 내려주었습니다
- NewGroup 페이지 컴포넌트의 상태에 groupCnt 프로퍼티를 추가하였습니다

Fix: Resolve create new group function

---

src/App.module.css
src/components/MainLayout/MainLayout.js
src/components/MainLayout/MainLayout.module.css
src/components/MainLayout/Nav.module.css
src/components/MainLayout/SignInAndOut.module.css
src/pages/Members/Members.module.css

Layout chaerin

---

library/CBD/component.js
library/CBD/eventHandler.js
library/CBD/render.js
server.js
src/App.js
src/components/Result/Members.js
src/pages/Members/MemberItem.js
src/pages/Members/MemberList.js
src/pages/Members/Members.js
src/pages/NewGroup/Result.js
src/pages/NewGroup/SelectGroupCnt.js
src/pages/Records/Records.js
src/pages/SignInSignUp/SignIn.js
src/pages/SignInSignUp/SignUp.js
src/state/index.js

- 전역상태와 지역상태를 같은 시점에 변경할 때 렌더링 버그가 생기는
부분을 수정하였습니다.
- 부분렌더링을 하는 구조로 바뀌면서, 전역상태를 먼저 수정한 뒤 지역
상태를 수정하는 경우 DOM Node를 제대로 참조하지 못하게 되었습니다.
- 일단 전역 상태를 수정한 뒤에는 렌더링에 영향을 미치는 함수를 호출하지
않도록 수정하였습니다.

Members style jaeyeong

---

src/App.module.css
src/components/MainLayout/MainLayout.module.css
src/components/Modals/Modal.module.css
src/components/Result/Groups.module.css
src/components/Result/Members.module.css
src/pages/Members/Members.module.css
src/pages/NewGroup/NewGroup.module.css
src/pages/SignInSignUp/SignIn.js
src/pages/SignInSignUp/SignInSignUp.module.css
src/pages/SignInSignUp/SignUp.js

CSS - chaerin

---

.env

fix: Fix untracked files

---

src/components/Result/Groups.js
src/components/Result/Members.js
src/pages/NewGroup/Result.js
src/pages/NewGroup/Result.module.css

- 컴포넌트의 클래스명 변경 및 태그 수정
- 드래그 시작 시 같은 컨텐이너 안에서 움직이면 무시하도록 수정
- change save logic
- delete unnecessary comments
- divert depending on dragtarget is member or group
- change swap function
- state 저장방식 변경

new DND - hyunjung

---

library/CBD/ComponentTree.js
library/CBD/component.js
library/CBD/eventHandler.js
library/CBD/index.js
library/CBD/render.js
library/CBD/state.js

- didMount / didUpdate / willUnmount 메서드 구현
- 생명주기 관리를 위해 컴포넌트 트리를 생성
- 이벤트 핸들러 등록 및 해제 로직 수정
- didMount시점에 등록
- willUnmount시점에 해제
close #49

feat: Implement life cycle method

---

package.json
server.js
vite.config.js

- server.js에서 process.env.NODE_ENV값에 따라 허용 origin을 설정하도록 하였습니다.
- 개발환경: 모든 오리진 허용
- 배포환경: 자사 도메인
- server 코드 수정으로 인해 불필요해진 vite config 코드를 삭제하였습니다
- vite 서버와 express 서버를 동시에 구동하도록 npm 명령어를 수정하였습니다
**앞으로 개발 환경에서는 'npm run dev' 명령어를 사용하시고, vite서버(5173포트)를 띄워놓고 작업하시면 됩니다**

fix: Resolve CORS error

---

.eslintrc.json
jsconfig.json
package-lock.json
package.json
src/App.js
src/apis/members.js
src/apis/organization.js
src/apis/records.js
src/pages/Members/Members.js
src/pages/Records/Records.js
src/pages/SignInSignUp/SignIn.js
src/pages/SignInSignUp/SignUp.js
src/utils/index.js
src/utils/sanitize.js

- @를 사용한 절대경로 import시 ctrl+click으로 모듈 파일을 찾아갈 수 없던 문제를 해결하였습니다
- 흩어져 있는 import문을 정리하였습니다
- 'sanitize-html' 라이브러리를 사용하여 모든 사용자 인풋에 sanitize를 적용하였습니다
- 옵션을 일괄적용하기 위해 util함수를 생성하였습니다

Feat: Sanitize inputs

---

src/App.module.css
src/components/MainLayout/MainLayout.module.css

- 화면 크기가 줄어들었을 때 오른쪽 마진이 사라지는 버그를 수정하였습니다
- 레이아웃 및 디자인적 여백을 마진에서 패딩으로 수정하고, 전체 너비의 최솟값을 지정하였습니다

Fix: Resolve disappear right-margin bug

---

library/CBD/render.js
package-lock.json
src/App.js
src/App.module.css
src/components/Counter/Counter.js
src/pages/Members/Members.js
src/pages/NewGroup/NewGroup.js
src/pages/NewGroup/NewGroup.module.css
src/pages/NewGroup/Result.js
src/pages/NewGroup/Result.module.css
src/pages/NewGroup/SelectGroupCnt.js

- 왼쪽 영역 너비 고정
- 그룹 계산하는 동안 로딩 메시지 보여주도록
- 불필요한 콘솔 제거
- 그룹 개수가 1로 유지되는 문제 해결
- 고스트 요소로 인해 세로 스크롤이 생기는 문제 해결

Show loading message when generating groups and Fix some errors
